remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
title: Cyclistic Case Study User Analysis
description: Google Data Analytics Case Study.
author: Uldur
show_downloads: false
